package com.flameking.community.mapper;

import com.flameking.community.entity.DiscussPost;
import com.flameking.community.entity.DiscussPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscussPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int countByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int deleteByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int insert(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int insertSelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    List<DiscussPost> selectByExampleWithBLOBs(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    List<DiscussPost> selectByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    DiscussPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByExampleSelective(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByExample(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByPrimaryKeySelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Sat Jul 16 17:11:35 CST 2022
     */
    int updateByPrimaryKey(DiscussPost record);
}