package com.flameking.community.mapper;

import com.flameking.community.entity.LoginTicket;
import com.flameking.community.entity.LoginTicketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int countByExample(LoginTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int deleteByExample(LoginTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int insert(LoginTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int insertSelective(LoginTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    List<LoginTicket> selectByExample(LoginTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    LoginTicket selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int updateByExampleSelective(@Param("record") LoginTicket record, @Param("example") LoginTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int updateByExample(@Param("record") LoginTicket record, @Param("example") LoginTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int updateByPrimaryKeySelective(LoginTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbggenerated Sat Jul 16 17:10:36 CST 2022
     */
    int updateByPrimaryKey(LoginTicket record);
}